<a href="https://colab.research.google.com/github/marce3-2140/numpy-exercises/blob/main/Copia_de_Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lida Marcela Giraldo**

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [2]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [3]:
distance = np.array([100, 200, 400, 800, 1500, 3000, 5000, 10000])

3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [4]:
print(np.min(distance))
print(np.max(distance))

100
10000


4) To find the average distance, use the np.mean() function

In [5]:
np.mean(distance)

2625.0

5) use the np.sum() function to find the total distance

In [6]:
np.sum(distance)

21000

6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [7]:
np.cumsum(distance)

array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

7) To round all of the values in an array, use np.round()

In [8]:
np.round(distance)

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [9]:
time = np.array([10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45])

9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [15]:
speed_olympians = distance/time #m/s
print(np.round(speed_olympians, 2))

[9.42 9.37 8.29 7.05 6.41 5.92 5.77 5.69]


10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [16]:
#convert from m/s to miles por hour

miles_per_hour = (speed_olympians*0.00062)*3600
print(np.round(miles_per_hour, 2))

[21.02 20.92 18.5  15.74 14.31 13.22 12.88 12.7 ]


In [33]:
#How do our olympians compare to the cheetah
for i in miles_per_hour:
  print(f"Speed olympians = {np.ceil(i).astype(int)} miles-per-hour is ",np.ceil(((i*100)/75.0).astype(int)),"% of speed cheetah of 75.0 miles-per-hour")


Speed olympians = 22 miles-per-hour is  28.0 % of speed cheetah of 75.0 miles-per-hour
Speed olympians = 21 miles-per-hour is  27.0 % of speed cheetah of 75.0 miles-per-hour
Speed olympians = 19 miles-per-hour is  24.0 % of speed cheetah of 75.0 miles-per-hour
Speed olympians = 16 miles-per-hour is  20.0 % of speed cheetah of 75.0 miles-per-hour
Speed olympians = 15 miles-per-hour is  19.0 % of speed cheetah of 75.0 miles-per-hour
Speed olympians = 14 miles-per-hour is  17.0 % of speed cheetah of 75.0 miles-per-hour
Speed olympians = 13 miles-per-hour is  17.0 % of speed cheetah of 75.0 miles-per-hour
Speed olympians = 13 miles-per-hour is  16.0 % of speed cheetah of 75.0 miles-per-hour
