<a href="https://colab.research.google.com/github/marce3-2140/numpy-exercises/blob/main/Copia_de_Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lida Marcela Giraldo**

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [1]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [2]:
distance = np.array([100, 200, 400, 800, 1500, 3000, 5000, 10000])

3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [3]:
print(np.min(distance))
print(np.max(distance))

100
10000


4) To find the average distance, use the np.mean() function

In [4]:
np.mean(distance)

2625.0

5) use the np.sum() function to find the total distance

In [5]:
np.sum(distance)

21000

6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [6]:
np.cumsum(distance)

array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

7) To round all of the values in an array, use np.round()

In [7]:
np.round(distance)

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [8]:
time = np.array([10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45])

9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [26]:
speed = distance/time #m/s
speed_mps = np.array(speed)
speed_mps

array([9.41619586, 9.37207123, 8.29015544, 7.0528079 , 6.41135237,
       5.92265019, 5.77253888, 5.69006231])

10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [28]:
#convert from m/s to miles por hour
speed_miles_per_hour = speed_mps*0.00062*3600
speed_mph = np.array(speed_miles_per_hour)
speed_mph

array([21.01694915, 20.91846298, 18.50362694, 15.74186723, 14.31013849,
       13.21935522, 12.88430678, 12.70021907])

In [38]:
# Compare the Olympic record speeds to the cheetah's speed
cheetah_speed = 75.0
for i in speed_mph:
  print(f"for Olympians speed: {np.ceil(i).astype(int)} miles/hour is {np.ceil((i*100)/cheetah_speed).astype(int)} % of Cheetah's speed of 75.0 miles/hour")


for Olympians speed: 22 miles/hour is 29 % of Cheetah's speed of 75.0 miles/hour
for Olympians speed: 21 miles/hour is 28 % of Cheetah's speed of 75.0 miles/hour
for Olympians speed: 19 miles/hour is 25 % of Cheetah's speed of 75.0 miles/hour
for Olympians speed: 16 miles/hour is 21 % of Cheetah's speed of 75.0 miles/hour
for Olympians speed: 15 miles/hour is 20 % of Cheetah's speed of 75.0 miles/hour
for Olympians speed: 14 miles/hour is 18 % of Cheetah's speed of 75.0 miles/hour
for Olympians speed: 13 miles/hour is 18 % of Cheetah's speed of 75.0 miles/hour
for Olympians speed: 13 miles/hour is 17 % of Cheetah's speed of 75.0 miles/hour


In [40]:
# Compare the Olympic record speeds to the cheetah's speed
for i in speed_mph:
  print(f"for olympians speed = {np.ceil(i).astype(int)} miles/hour Cheetah's speed is {np.ceil(cheetah_speed /i).astype(int)} times faster")

for olympians speed = 22 miles/hour Cheetah's speed is 4 times faster
for olympians speed = 21 miles/hour Cheetah's speed is 4 times faster
for olympians speed = 19 miles/hour Cheetah's speed is 5 times faster
for olympians speed = 16 miles/hour Cheetah's speed is 5 times faster
for olympians speed = 15 miles/hour Cheetah's speed is 6 times faster
for olympians speed = 14 miles/hour Cheetah's speed is 6 times faster
for olympians speed = 13 miles/hour Cheetah's speed is 6 times faster
for olympians speed = 13 miles/hour Cheetah's speed is 6 times faster


These values indicate that the speed of the Cheetah is between 4 and 6 times faster than that of Olympic runners.