<a href="https://colab.research.google.com/github/marce3-2140/numpy-exercises/blob/main/Panaderia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Unos jovenes de un club de tecnologia les pide ayuda para analizar datos de su venta de pasteles. Esperan reunir $200

Lista de Precios:

```
1.  $2 por un brownie
2.  $1 por una galleta
3.  $10 por un pastel
```

El club vende 17 brownies, 40 galletas y un pastel





In [ ]:
#Lista de precios
price = [2, 1, 10]

#lista de cantidades vendidas
quantity_sold = [17, 40, 1]

Ahora, encontramos el dinero recaudado para cada tipo de elemento.

In [ ]:
import numpy as np

In [ ]:
#convertir una lista a un array de numpy

price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)

In [ ]:
#hacemos operaciones entre los array

price_array * quantity_sold_array

array([34, 40, 10])

Ahora, revisemos los costos de fabricacion de cada elemento de la venta.


```
1. cada brownie cuesta hacerlo $0.25.
2. Cada Galleta cuesta hacerlo $0.50
3. Cada pastel cuesta hacerlo $5
```

In [ ]:
#hacemos una lista de los costos y la convertimos a array

cost_array = np.array([0.25, 0.50, 5.00])

In [ ]:
#to find the profit of each ithem, we want to subtract the cost from the price.

profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


In [ ]:
#Queremos identificar que elementos obtuvieron un beneficio superior a $2 por elemento.

profit_array > 2

array([False, False,  True])

In [ ]:
#agregamos un nuevo producto: tartas a $7, actualizamos el price_array

price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


In [ ]:
#agregamos varios productos en una sola linea
#$4.50 por dulces, $3 por una magdalena, $4 por una barra de pan de banano y $9 por una torta

price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [ ]:
print(price_array.dtype)

float64


In [ ]:
#queremos eliminar el precio de la torta con np.delete

price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [ ]:
#el club sube el precio de los pasteles de $10 a $12
#identificamos que el indice de los pasteles esta en el indice 2.

price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


# Parte II del ejercicio

**2. actualizamos quantity_sold_array para incluir a la venta:**


**a).**  2 tartas, 3 bandejas de dulces,, 16 magdalenas y 5 panes de banano.


**b).** de las galletas que pensaron que vendieron en realidad una se cayo al suelo
    asi que editen quantity_sold de 40 a 39.

In [ ]:
#agregamos otras ventas
quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
print(quantity_sold_array)

[17 40  1  2  3 16  5]


In [ ]:
#modificamos la cantidad vendida de galletas restamos la que se cayo al suelo.
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


**3. determinen la cantidad de dinero recaudado de la venta de cada elemento en la venta de la panaderia**

In [ ]:
#Determinamos la cantidad total de dinero de venta precio total

venta_precio_total = quantity_sold_array * price_array
print(venta_precio_total)

[34.  39.  12.  14.  13.5 48.  20. ]


**4. Creen un array de Numpy "quantity_leftover" que incluya la cantidad de cada elemento restante al final de la venta:**

1. 2 Pasteles
2. 1 tarta
3. 6 bandejas de dulces
4. 2 panes de banano.

Asegurese de incluir 0 de cada elemento que se haya vendido

In [ ]:
#Cantidad restante de cada elemento al final de la venta

quantity_leftover = np.array([0, 0, 2, 1, 6, 0, 2])

In [ ]:
#Venta de liquidacion donde cada elemento lo venden a mitad de precio.
venta_liquidacion = quantity_leftover*(price_array*0.5)
print(venta_liquidacion)

[ 0.   0.  12.   3.5 13.5  0.   4. ]


In [ ]:
#sumamos la venta de liquidacion con la venta del precio total
venta_total = venta_liquidacion + venta_precio_total
print(venta_total)

[34.  39.  24.  17.5 27.  48.  24. ]


In [ ]:
#Venta Total
print(sum(venta_total))

213.5
